### ISSUE TITLE
[Feature Request] Firefox for android support

### ISSUE THREAD

**Issue by namesarebloat** [onurhanak/Break-Down-Walls#1]
Hello! First and foremost, thank you for this extension.

[Since Mozilla recently opened up their android versions to add-ons again](https://blog.mozilla.org/addons/2023/12/14/a-new-world-of-open-extensions-on-firefox-for-android-has-arrived/), maybe this add-on could be updated to work on mobile? 

I managed to install it [by adding a custom collection](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/), but it doesn't show up in the context menu and accessing its functionality through ⋮ > Add-ons > Break Down Walls also doesn't work (nothing happens at all). The settings page can be accessed though.

I verified that the extension can find the study, that I used for testing, on desktop firefox, because I don't know if the error notifications would work on android.

**Comment by onurhanak** [comment]
Thanks for engaging with the project! This seems like a great idea, will implement.

**Comment by onurhanak** [comment]
Done. Version 1.2.5 should be available in a couple of hours. Please test and report back. Thanks.
